function RHEOL = load_rheol(RHEOL)

  % LOAD_RHEOL is a script containing the rheologies used by the code. It
  % uses the variable RHEOL.type to choose among the different rheologies with
  % a switch. To add a new rheology make a new "case" in the switch.

  Bdis_w = RHEOL.Bdis_w;
  Bdif_w = RHEOL.Bdif_w; 
  Bdis_d = RHEOL.Bdis_d;
  Bdif_d = RHEOL.Bdif_d;

  switch RHEOL.type
    case 'hk_lc_gr'
        %% MAFIC GRANULITE LOWER CRUST (WET OLIVINE TO DRY OLIVINE MANTLE)
        %'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
        %MANTLE VALUES FROM HIRTH AND KOHLSTEDT 2003 (WET TO DRY OLIVINE)
        %LOWER CRUST VALUES FROM WILKS AND KARTER 1990 (MAFIC GRANULITE)
        %UPPER CRUST VALUES FROM GLEASON AND TULLIS 1995 (WET QUARTZITE)
        %==================================================================
        % DISLOCATION
        %==================================================================
        RHEOL.Adis  = [ Bdis_w          Bdis_d; ...
            10^(-21.05)     10^(-21.05); ...
            10^(-28.00)     10^(-28.00)]; % Pa^-n*s^-1
        RHEOL.Ndis  = [ 3.5             3.5; ...
            4.2             4.2; ...
            4.0             4.0]; % Power law exponent
        RHEOL.Qdis  = [ 480e3           530e3; ...
            445e3           445e3; ...
            223e3           223e3]; % Activation energy
        RHEOL.Vdis  = [ 10e-6           13e-6; ...
            0                 0; ...
            0                 0]; % Activation volume
        %==================================================================
        % DIFUSSION
        %==================================================================
        %DIFFUSION FLOW LAWS ARE ALL FOR OLIVINE
        RHEOL.Adif  = [ Bdif_w      	Bdif_d; ...
            0               0; ...
            0               0]; % Pa^-1*s^-1
        RHEOL.Ndif  = [ 1               1; ...
            0               0; ...
            0               0]; % Power law exponent
        RHEOL.Qdif  = [ 335e3           375e3; ...
            0               0; ...
            0               0]; % Activation energy
        RHEOL.Vdif  = [ 4e-6            6e-6; ...
            0               0; ...
            0               0]; % Activation volume
    case 'hk_lc_an'
        %% WET ANORTHITE LOWER CRUST (WET OLIVINE TO DRY OLIVINE MANTLE)
        %'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
        %MANTLE VALUES FROM HIRTH AND KOHLSTEDT 2003 (WET TO DRY OLIVINE)
        %LOWER CRUST VALUES FROM RYBACKI AND DRESEN 2000 (WET ANORTHITE)
        %UPPER CRUST VALUES FROM GLEASON AND TULLIS 1995 (WET QUARTZITE)
        %==================================================================
        % DISLOCATION
        %==================================================================
        RHEOL.Adis  = [ Bdis_w          Bdis_d; ...
            10^(-15.40)     10^(-15.40); ...
            10^(-28.00)     10^(-28.00)]; % Pa^-n*s^-1
        RHEOL.Ndis  = [ 3.5             3.5; ...
            3.0             3.0; ...
            4.0             4.0]; % Power law exponent
        RHEOL.Qdis  = [ 480e3           530e3; ...
            356e3           356e3; ...
            223e3           223e3]; % Activation energy
        RHEOL.Vdis  = [ 10e-6           13e-6; ...
            0                 0; ...
            0                 0]; % Activation volume
        %==================================================================
        % DIFUSSION
        %==================================================================
        %DIFFUSION FLOW LAWS ARE ALL FOR OLIVINE
        RHEOL.Adif  = [ Bdif_w      	Bdif_d; ...
            0               0; ...
            0               0]; % Pa^-1*s^-1
        RHEOL.Ndif  = [ 1               1; ...
            0               0; ...
            0               0]; % Power law exponent
        RHEOL.Qdif  = [ 335e3           375e3; ...
            0               0; ...
            0               0]; % Activation energy
        RHEOL.Vdif  = [ 4e-6            6e-6; ...
            0               0; ...
            0               0]; % Activation volume
    case 'hk_lc_wq'
        %% WET QUARTZITE LOWER CRUST (WET OLIVINE TO DRY OLIVINE MANTLE)
        %'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
        %MANTLE VALUES FROM HIRTH AND KOHLSTEDT 2003 (WET TO DRY OLIVINE)
        %LOWER CRUST VALUES FROM GLEASON AND TULLIS 1995 (WET ANORTHITE)
        %UPPER CRUST VALUES FROM GLEASON AND TULLIS 1995 (WET QUARTZITE)
        %==================================================================
        % DISLOCATION
        %==================================================================
        RHEOL.Adis  = [ Bdis_w          Bdis_d; ...
            10^(-28.00)     10^(-28.00); ...
            10^(-28.00)     10^(-28.00)]; % Pa^-n*s^-1
        RHEOL.Ndis  = [ 3.5             3.5; ...
            4.0             4.0; ...
            4.0             4.0]; % Power law exponent
        RHEOL.Qdis  = [ 480e3           530e3; ...
            223e3           223e3; ...
            223e3           223e3]; % Activation energy
        RHEOL.Vdis  = [ 10e-6           13e-6; ...
            0                 0; ...
            0                 0]; % Activation volume
        %==================================================================
        % DIFUSSION
        %==================================================================
        %DIFFUSION FLOW LAWS ARE ALL FOR OLIVINE
        RHEOL.Adif  = [ Bdif_w      	Bdif_d; ...
            0               0; ...
            0               0]; % Pa^-1*s^-1
        RHEOL.Ndif  = [ 1               1; ...
            0               0; ...
            0               0]; % Power law exponent
        RHEOL.Qdif  = [ 335e3           375e3; ...
            0               0; ...
            0               0]; % Activation energy
        RHEOL.Vdif  = [ 4e-6            6e-6; ...
            0               0; ...
            0               0]; % Activation volume

    case 'all_peridotite'
        %'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
        %MANTLE VALUES FROM HIRTH AND KOHLSTEDT 2003 (WET TO DRY OLIVINE)
        %LOWER CRUST VALUES SET TO DRY MANTLE
        %UPPER CRUST VALUES SET TO DRY MANTLE
        %==================================================================
        % DISLOCATION
        %==================================================================
        RHEOL.Adis  = [ Bdis_w          Bdis_d; ...
                        Bdis_d          Bdis_d; ...
                        Bdis_d          Bdis_d]; % Pa^-n*s^-1
        RHEOL.Ndis  = [ 3.5             3.5; ...
                        3.5             3.5; ...
                        3.5             3.5];    % Power law exponent
        RHEOL.Qdis  = [ 480.e3          530.e3; ...
                        530.e3          530.e3; ...
                        530.e3          530.e3];  % Activation energy
        RHEOL.Vdis  = [ 10.e-6          13.e-6; ...
                        13.e-6          13.e-6; ...
                        13.e-6          13.e-6];  % Activation volume
        %==================================================================
        % DIFUSSION
        %==================================================================
        %DIFFUSION FLOW LAWS ARE ALL FOR OLIVINE
        RHEOL.Adif  = [ Bdif_w      	Bdif_d; ...
                        Bdif_d      	Bdif_d; ...
                        Bdif_d      	Bdif_d]; % Pa^-1*s^-1
        RHEOL.Ndif  = [ 1               1; ...
                        1               1; ...
                        1               1];      % Power law exponent
        RHEOL.Qdif  = [ 335.e3          375.e3; ...
                        375.e3          375.e3; ...
                        375.e3          375.e3];  % Activation energy
        RHEOL.Vdif  = [ 4.e-6           6.e-6; ...
                        6.e-6           6.e-6; ...
                        6.e-6           6.e-6];   % Activation volume
    
    case 'verylow_everywhere'
        % '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
        %very low values to test rapid recovery of topography for hydroload test with rho_w=0
        %==================================================================
        % DISLOCATION
        %==================================================================
        RHEOL.Adis  = [10^(-18.00)  10^(-18.00); ...
                       10^(-20.00)  10^(-20.00); ...
                       10^(-21.00)  10^(-21.00)]; % Pa^-n*s^-1
        RHEOL.Ndis  = [ 1.0  1.0; ...
                        1.0  1.0; ...
                        1.0  1.0]; % Power law exponent
        RHEOL.Qdis  = [ 23e3  23e3; ...
                        23e3  23e3; ...
                        23e3  23e3]; % Activation energy
        RHEOL.Vdis  = [ 0   0; ...
                        0   0; ...
                        0   0]; % Activation volume
        %==================================================================
        % DIFUSSION
        %==================================================================
        %DIFFUSION FLOW LAWS ARE ALL FOR OLIVINE
        RHEOL.Adif  = [ 0      	0; ...
                        0      	0; ...
                        0      	0]; % Pa^-1*s^-1
        RHEOL.Ndif  = [ 0       0; ...
                        0       0; ...
                        0       0];      % Power law exponent
        RHEOL.Qdif  = [ 0       0; ...
                        0       0; ...
                        0       0];  % Activation energy
        RHEOL.Vdif  = [ 0       0; ...
                        0       0; ...
                        0       0];   % Activation volume
  end % switch
end % function

